# Factory World Coordinates

supermarket:
  x: 0.0
  y: 0.0

assembly_cells:
  cell_a:
    x: 0.0
    y: 0.0

  cell_b:
    x: 0.0
    y: 0.0

  cell_c:
    x: 0.0
    y: 0.0

amr_home:
  x: 0.0
  y: 0.0
